sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nahuakang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nahuakang/react-test npm test

after_success:
  - docker build -t nahuakang/multi-container-client ./client
  - docker build -t nahuakang/multi-container-nginx ./nginx
  - docker build -t nahuakang/multi-container-server ./server
  - docker build -t nahuakang/multi-container-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to Docker Hub
  - docker push nahuakang/multi-container-client
  - docker push nahuakang/multi-container-nginx
  - docker push nahuakang/multi-container-server
  - docker push nahuakang/multi-container-worker
